### DISCUSSION TITLE
Tested C# tests timeout

### DISCUSSION THREAD

**Discussion by Brechtvsk** [dodona-edu/feedback-and-support#114] [Bug reports] [answered]
I'm writing samples in C# and trying to test them with the universal judge (tested). The tests always fail giving a `compilation error`. 
When testing with default settings the error occurs after 40s, when the `time_limit` setting si increased to 90, the error occurs after 90s (give or take). For some reason the time_limit always gets exceeded and it fails. No details are given in the error.
The sample code I'm trying to test:
```csharp
using System;

public class Program
{
    public static void Main(string[] args)
    {
            string userName = Console.ReadLine();
        System.Console.WriteLine("Hello, " + userName + "!");
    }
}
```

the test suite:
```yaml
namespace: Program
tabs:
- tab: "Testen"
  testcases:
    - stdin: "Jan"
      stdout: "Hallo, Jan!"
    - stdin: "Piet"
      stdout: "Hallo, Piet!"
    - stdin: "5236-hallo!"
      stdout: "Hallo, 5236-hallo!!"
    - stdin: "'wereld'"
      stdout: "Hallo, 'wereld'!"
    - stdin: '"wereld"'
      stdout: 'Hallo, "wereld"!'
    - stdin: "    "
      stdout: "Hallo,     !"
```
