### DISCUSSION TITLE
Stuck on input-output evaluation YAML-file

### DISCUSSION THREAD

**Discussion by antonthys** [dodona-edu/feedback-and-support#25] [Questions - Vragen] [answered]
Hi, 

I'm struggling with creating a correct suite.yaml file for evaluation of an programming exercise where the students are asked to make a code that calculates the area of a trapezoid based on 3 inputs: 

```
a = int(input("length of long base: "))
b = int(input("length of short base: "))
h = int(input("height of trapezium"))
area = 0.5*(a+b)*h
print(area)
```

As you can see python asks the user for 3 inputs. I tried creating a suite.yaml file with 1 test as follows: 

```

- tab: oppervlakte-trapezium
  testcases:
    - stdin: "1", "2", "3"
      stdout: 4.5
```
but this clearly doesn't work because of the **stdin: "1", "2", "3"**. 

I have no idea how to fix this error though? Any ideas how to write a correct yaml-file that would work for this code? 

Many thanks in advance!

**Comment by niknetniko** [comment, marked as answer]
The `input()` function in Python always reads a single line from `stdin`. This means that if you want to pass three inputs, you need to put three lines on `stdin`:

```yaml
- tab: oppervlakte-trapezium
  testcases:
    - stdin: |
        1
        2
        3
      stdout: 4.5
```

The `|` in YAML is a special syntax to write multiple lines. Alternatively, you can be explicit:

```yaml

- tab: oppervlakte-trapezium
  testcases:
    - stdin: "1\n2\n3"
      stdout: 4.5
```
