### DISCUSSION TITLE
Advanced return type (tuple) - how to use?

### DISCUSSION THREAD

**Discussion by DieterPi** [dodona-edu/feedback-and-support#37] [Questions - Vragen] [answered]
According to the [docs](https://docs.dodona.be/nl/references/tested/types/) TESTed has support for the immutable sequence `tuple`.  Does this mean I can test if my pupils have a function which properly returns tuples instead of lists?

I've tried (mimicking the [full example](https://docs.dodona.be/nl/references/tested/dsl/#volledig-voorbeeld))

```
- expression: RGB( (0,128,128) )
  return: "tuple( (255, 127, 127) )"
```

instead of
```
- expression: RGB( (0,128,128) )
  return:
  - 255
  - 127
  - 127
```

since the last example would also approve of a `list` with the values...

**Comment by niknetniko** [comment, marked as answer]
> Does this mean I can test if my pupils have a function which properly returns tuples instead of lists?

Yes, this is possible.

> I've tried (mimicking the [full example](https://docs.dodona.be/nl/references/tested/dsl/#volledig-voorbeeld))

It seems these docs are slightly out-of-date: they are missing a required YAML tag. My apologies for that.

There are a few equivalent ways of doing this:

```yaml
- expression: RGB((0, 128, 128))
  return: !expression "(255, 127, 127)"
- expression: RGB((0, 128, 128))
  return: !expression "tuple((255, 127, 127))"
- expression: RGB((0, 128, 128))
  return: !tuple [255, 127, 127]
- expression: RGB((0, 128, 128))
  return: !tuple
    - 255
    - 127
    - 127
```

You are correct that your last example will accept both `list` and `tuple` in Python (and e.g. `List` and `array` in Java).
