### DISCUSSION TITLE
TESTed: Oefeningen opstellen in C#

### DISCUSSION THREAD

**Discussion by bmesuere** [dodona-edu/feedback-and-support#42] [Questions - Vragen] [answered]
We kregen deze vraag via email:

> Ik probeer met TESTed een C# oefening op te stellen, maar krijg telkens compilatiefouten. Dit is de code die zou moeten uitgevoerd worden:
```C#
using System;

public class Program
{
    public static void Main(string[] args)
    {
            string userName = Console.ReadLine();
        System.Console.WriteLine("Hello, " + userName + "!");
    }
}
```

**Comment by bmesuere** [comment, marked as answer]
De klasse waarin de oplossing komt wordt bepaald door de "namespace" in het testplan.
In dit geval is er geen, dus wordt de standaardwaarde gebruikt, namelijk Submission.

Je moet dus ofwel de oplossing aanpassen als volgt:

```C#
using System;

public class Submission
{
    public static void Main(string[] args)
    {
       string userName = Console.ReadLine();
        System.Console.WriteLine("Hello, " + userName + "!");
    }
}
```

Of je moet het testplan aanpassen als volgt:
```yaml
namespace: Program
tabs:
- tab: "Testen"
  testcases:
    - stdin: "Jan"
      stdout: "Hallo, Jan!"
    - stdin: "Piet"
      stdout: "Hallo, Piet!"
    - stdin: "5236-hallo!"
      stdout: "Hallo, 5236-hallo!!"
    - stdin: "'wereld'"
      stdout: "Hallo, 'wereld'!"
    - stdin: '"wereld"'
      stdout: 'Hallo, "wereld"!'
    - stdin: "    "
      stdout: "Hallo,     !"
```
