### DISCUSSION TITLE
TESTed: uitvoer testen zonder newlines

### DISCUSSION THREAD

**Discussion by bmesuere** [dodona-edu/feedback-and-support#43] [Questions - Vragen] [answered]
We kregen deze vraag via email:

> Ik heb een oefening waar de uitvoer naar stdout niet eindigt op een newline. Ondanks dat mijn testen deze newlines niet bevatten, verwacht Dodona ze toch. Hoe kan ik dit oplossen?
> ![image](https://github.com/user-attachments/assets/28bb2a13-fff3-4d25-bdfa-1a12fd1d9340)

**Comment by bmesuere** [comment, marked as answer]
TESTed zal inderdaad standaard een newline toevoegen aan de verwachte uitvoer (als deze geen bevat). Dit omdat uitvoer naar stdout meestal eindigt op een newline en dit het schrijven van de testen beknopter maakt. Het is echter mogelijk om dit gedrag uit te schakelen met de config vlag `normalizeTrailingNewlines`:

```yaml
- tab: "Tel klinkers"
  config:
    stdout:
      normalizeTrailingNewlines: false
  testcases:
    - expression: "positie_klinkers('Always look on the bright side of life!')"
      stdout: "0 3 8 9 12 17 21 27 29 31 35 37 "
    - expression: 'positie_klinkers("Python fits your brain")'
      stdout: "4 8 13 14 19 20 "
```
