### DISCUSSION TITLE
Trying out Class support in C#

### DISCUSSION THREAD

**Discussion by svrstich** [dodona-edu/feedback-and-support#48] [Questions - Vragen]
Dear colleagues,
In the context of the course Object Oriented Programming, I'm now finally trying to get these exercises into Dodona as well. I started with the example in Python: https://docs.dodona.be/nl/guides/exercises/examples/class/
However, I think I might be missing something. Hence the reason for posting here ;-)

This is the link to the exercise: https://dodona.be/nl/courses/4088/series/49751/activities/1888217412/

I'm stuck with a compilation error, without further details. It might be some namespace issues, I dunno. Could you point me in the right direction? Would be greatly appreciated!

Regards
Stijn

![image](https://github.com/user-attachments/assets/6140b367-908b-4e91-a022-d4274c641970)

**Comment by jorg-vr** [comment]
Our language for writing tests is the same for every programing language. This is also true for the statements.
For the actual statements, our syntax is mostly equivalent to the python syntax. (You can find some detailed info about that her https://docs.dodona.be/nl/guides/exercises/testsuites/#formaat)

Concretly for your exercise. You have specified the following `suite.yaml`:
```yaml
- tab: "Counter"
  contexts:
    - testcases:
        - statement: "Counter c = new Counter(5);"
        - statement: "c.Report();"
          stdout: "5"
        - statement: "c.Count();"
        - statement: "c.Report();"
          stdout: "6"
        - statement: "c.Count().Count().Count().Count().Report();"
          stdout: "10"
```
Here you use the C# syntax to specify the statements which need to be executed. Which results in compilation errors when we try too parse it.

To solve this, you have two choices:
1. Use the python syntax
```yaml
- tab: "Counter"
  contexts:
    - testcases:
        - statement: "counter = Counter(5)"
        - statement: "counter.report()"
          stdout: "5"
        - statement: "counter.count()"
        - statement: "counter.report()"
          stdout: "6"
        - statement: "counter.count().count().count().count().report()"
          stdout: "10"
 ```
 This test as given in the example should simply work for C# without any changes. We will translate the statements to C# statements in the background.
 
 2. Specify that you are declaring your statements in csharp
If the pythonic syntax doesn't offer enough support for a required c# feature, you can specify C# statements instead.
This is more advanced and not advised, as it also becomes more complex with determining namespaces.
More info on how to do this can be found here: https://docs.dodona.be/nl/guides/exercises/testsuites/#taalspecifieke-expressies-en-statements
